### ISSUE TITLE
Fix scrolling JS errors on documentation page

### ISSUE THREAD

**Issue by FinnLawrence** [concordion/concordion-website#12]
The Javascript that controls the navigation on the homepage is throwing errors on the documentation pages as the elements it looks for do not exist. This needs to be tweaked

**Comment by nigelcharman** [comment]
Currently the links are doing a redirect - need to change them to be real URLs - suggest we just direct to the Java/Markdown version of the docs by default

**Comment by nigelcharman** [comment]
@FinnLawrence would you check this is fixed for you now please
