### ISSUE TITLE
Link IntelliJ Markdown Plugin is broken

### ISSUE THREAD

**Issue by danielkocot** [concordion/concordion-website#41]
Regarding to the IntelliJ plugin page the recommended plugin is not available anymore. So the link is broken. Should there be a link to Markdown Navigator plugin?

**Comment by idegtiarenko** [comment]
I would recommend [Markdown support](https://plugins.jetbrains.com/plugin/7793?pr=idea) as it is vendored by jetbrains.

**Comment by nigelcharman** [comment]
I'll link to both. Do we have any recommendations for which one works better with Concordion?

**Comment by idegtiarenko** [comment]
Well, they both should work same, but I have spent more time testing Markdown support integration and Markdown Navigator integration was introduced only last release.

**Comment by nigelcharman** [comment]
@danielgrycman thanks for reporting this.

I've tried the updated Markdown Support plugin and it is much improved, so I agree about recommending it. It  now supports tables and strikethrough and doesn't crash like it used to!

I'll update the documentation accordingly.

Let us know of any feedback you have about the relative merits of the two plugins, or any further documentation enhancements.

**Comment by nigelcharman** [comment]
Fixed in 94ab2b25.
