### ISSUE TITLE
Tutorial explanation for writing fixtures with ArrayList

### ISSUE THREAD

**Issue by kalessL** [concordion/concordion-website#56]
Hello,
I have just started discovering Concordion, I'm following the [tutorial ](http://concordion.org/instrumenting/java/markdown/) however upon arriving to 'verify-rows command', we are task to search system. 

Search is mostly done with Arraylist, but at this point I still don't know how to write the fixture that extract an ArrayList to work with from the .md file.
I think the tutorial will gain in clarity (especialy for new comers) , if you were to add in this case the fixture used to test the search system was shared.

**Comment by nigelcharman** [comment]
Thanks for reporting this.

I've added a new [Advanced Tutorial](http://concordion.org/tutorial/java/markdown/#advanced) section containing the fixture for the `verify-rows` command. Would you review this please and provide feedback?

**Comment by kalessL** [comment]
Ok thanks it helped me.
Though, as you still are in the first page of the tutorial, I think it wouldn't hurt to add a sentence reminding people that the fixture should ultimately call for a method in the SUT (src/main/...) instead of solving the test.

For after learning the first steps, you should use fixture as bridge between the specification and the application (SUT) at least from my understanding. The same way we do with cucumber.

Overall I approuve the new section.
