### ISSUE TITLE
No DNS record for www.concordion.org 

### ISSUE THREAD

**Issue by robd** [concordion/concordion-website#69]
Just thought I should mention that it looks like the DNS record for the `www` version of the domain seems to be missing. I updated wikipedia to point to `concordion.org`, but it might be worth reinstating this since I think quite a few links point to the `www` version.

**Comment by nigelcharman** [comment]
Thanks for reporting it Rob. It must have happened in the switchover to https last week. I've added name records for www.concordion.org now. Thanks for updating wikipedia too.
