### ISSUE TITLE
How to start concordion manually?

### ISSUE THREAD

**Issue by knuthie** [concordion/concordion-website#71]
Hi,
I wanted to know if it is possible to start concordion without the help of gradle/maven. Is there a way to call a "main" class with parameters to start the testing per script? - Reason is, we are currently looking for a testframework we can use for a customer project to do regression tests on a customer system and there is no gradle, etc. installed, just our software and plain java.

**Comment by nigelcharman** [comment]
Thanks for raising this. I've added some documentation to the website for this. Would you review and let me know if this is sufficient - https://concordion.org/integrations/java/markdown/#command-line.

**Comment by knuthie** [comment]
Thanks Nigel, the documentation is spot on. I got it to work with the section you added.
