### ISSUE TITLE
Broken xsd schema link

### ISSUE THREAD

**Issue by xobotun** [concordion/concordion-website#91]
Many pages have references to http://www.concordion.org/2007/concordion, like https://concordion.org/instrumenting/java/html/, but it appears to be dead, returning 404 via both browser and IDEA.

Is support to the 2007 schema dropped? I can't find a new one anywhere.

**Comment by nigelcharman** [comment]
Hi, http://www.concordion.org/2007/concordion is an XML namespace name, not an XML Schema.

We don't have a schema for Concordion, which uses the XHTML schema with additional attributes in the http://www.concordion.org/2007/concordion namespace. There doesn't appear to be any support for having a schema that adds attributes to XHTML.

I've added a page to http://www.concordion.org/2007/concordion that clarifies this. I hope that helps?

**Comment by xobotun** [comment]
Oh, so it was a misunderstanding on my part. It didn't occur to me not all `xmlns` are provided with schemas.

Thank you for clarifying that!

I have very unstable foundational knowledge in the world of xml schemas, sorry. :)

---

On a side note, I copied a minimal XHTML 2.0 schema provided by W3C here: https://www.w3.org/MarkUp/SCHEMA/xhtml2.xsd
```
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.concordion.org/2007/concordion"
        elementFormDefault="unqualified">
    
    <!-- <xs:import namespace="http://www.w3.org/2002/06/xhtml2/" schemaLocation="https://www.w3.org/MarkUp/SCHEMA/xhtml2.xsd"/> -->
    <xs:annotation>
        <xs:documentation>
            A minimal XML Schema for XHTML 2.0
            $Id: xhtml2.xsd,v 1.4 2005/06/14 15:28:27 mimasa Exp $
        </xs:documentation>
    </xs:annotation>

    <xs:element name="html">
        <xs:complexType>
            <xs:sequence>
                <xs:any namespace="##any" processContents="skip"
                        minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:anyAttribute namespace="##any" processContents="skip"/>
        </xs:complexType>
    </xs:element>
</xs:schema>
```
And linked it within my project, so IDEA does not highlight my `html` and `body` tags as unknown.
